# Generated by Django 6.0.3 on 2026-04-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fowl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.CharField(max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('vaccination_status', models.CharField(default='Fully Vaccinated', max_length=200)),
                ('feeding_type', models.CharField(blank=True, max_length=200)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='fowls/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fowls', to='fowls.breed')),
            ],
        ),
        migrations.CreateModel(
            name='FowlImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fowls/gallery/')),
                ('fowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fowls.fowl')),
            ],
        ),
    ]
