# Generated by Django 6.0.3 on 2026-04-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fowls', '0002_category_remove_fowl_breed_remove_fowlimage_fowl_and_more'),
        ('orders', '0002_remove_order_fowl_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fowl',
        ),
        migrations.DeleteModel(
            name='FowlImage',
        ),
    ]
