# Generated by Django 6.0.3 on 2026-04-05 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fowls', '0003_delete_fowl_delete_fowlimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='fowls.breed'),
        ),
    ]
