# Generated by Django 6.0.3 on 2026-04-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fowls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('MTN', 'Mobile Money (MTN)'), ('ORANGE', 'Mobile Money (Orange)'), ('BANK', 'Bank Transfer')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('fowl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fowls.fowl')),
            ],
        ),
    ]
