# Generated by Django 6.0.3 on 2026-04-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fowls', '0004_alter_product_breed'),
        ('orders', '0002_remove_order_fowl_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK', 'E Transfer/paypal'), ('PAYPAL', 'PayPal Checkout'), ('CHIME', 'Chime'), ('ZELLE', 'Zelle'), ('VENMO', 'Venmo'), ('CASHAPP', 'Cash App'), ('APPLE', 'Apple Card'), ('WIRE', 'Wire Transfer'), ('CRYPTO', 'Cryptocurrency')], max_length=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='fowls.product')),
            ],
        ),
    ]
